UPDATE "User" SET "role" = 'SALES_SUPPORT', "tier" = 'TIER5_SALES_SUPPORT'
WHERE "role" = 'SYSTEM_ADMIN' OR "tier" = 'TIER5_SYSTEM_ADMIN';

UPDATE "InviteToken" SET "role" = 'SALES_SUPPORT'
WHERE "role" = 'SYSTEM_ADMIN';